baseurl = "https://lisefrac.net"
copyright = "© Lise Fracalossi"
title = "Lise Fracalossi"
enablerobotstxt = true
languagecode = "en-us"
paginate = 50
timezone = "America/New_York"
titlecasestyle = "Go"

[[module.imports]]
path = "github.com/willfaught/paige"

[markup.goldmark.renderer]
unsafe = true

[paige]
color = "#660033"
external_link_new_tab = true

[paige.analytics]
disable = true # Disable all analytics

[paige.comments]
disable = true # Disable all comments

[params.paige]
style = "#paige-page # { width: 66ch; }"

[paige.menu]
style = "links" # Must be "links", "pills", "tabs", or "underline"

[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "about"
name = "About Lise"
url = "/about/"
weight = 20


